### ISSUE TITLE
Issue in RecursionCustomization

### ISSUE THREAD

**Issue by ehjelholt** [atc-net/atc-test#30]
@davidkallesen the first statement in _**src/Atc.Test/Customizations/RecursionCustomization.cs**_ doesn't seem to do anything.
An object instance is removed which was never added to .Behaviors in the first place.
It still works since the code in OmitOnRecursionBehavior is run first and the (still remaining) ThrowingRecursionBehavior is never hit.

This code snippet will do the trick:

fixture.Behaviors  
   .OfType<ThrowingRecursionBehavior>()
   .ToList()
   .ForEach(b => fixture.Behaviors.Remove(b));

**Comment by davidkallesen** [comment]
@rickykaare will you take a look on this good input from @ehjelholt :-)

**Comment by rickykaare** [comment]
That's correct @ehjelholt. Wonder how this was not spotted in the last 2,5 years :-) 

Fix is here: #31
