### ISSUE TITLE
No need for this Library to Target .NET 5.0

### ISSUE THREAD

**Issue by kimlundjohansen** [atc-net/atc-test#9]
Most of our consumer projects still target .NET 3.1 and therefore targeting .NET 5.0 is still a bit premature.

**Comment by perkops** [comment]
@kimlundjohansen 

The project should be downgraded in the src/Directory.Build.props file - <TargetFramework>netstandard2.1</TargetFramework>

is it not working when referencing the package?

**Comment by kimlundjohansen** [comment]
Seems like a new release will solve the issue.
